// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnet_core_efcore_demo.Models;

namespace aspnet_core_efcore_demo.Migrations
{
    [DbContext(typeof(YpfDbContext))]
    [Migration("20200809113019_testsqlite")]
    partial class testsqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("aspnet_core_efcore_demo.Models.RoleInfor", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("roleDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("roleName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("RoleInfors");
                });

            modelBuilder.Entity("aspnet_core_efcore_demo.Models.UserInfor", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.Property<string>("userSex")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserInfors");
                });
#pragma warning restore 612, 618
        }
    }
}
